import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  es: {
    // Generales
    cancelar: "Cancelar",
    guardar: "Guardar",
    buscar: "Buscar",
    ok: "Aceptar",
    si: "Sí",
    no: "No",
    estado: "Estado",
    cargando: "Cargando...",
    error: "Error",
    advertencia: "Advertencia",
    cerrar: "Cerrar",

    // Header
    pruebas_elevacion: "PRUEBAS DE ELEVACIÓN",
    automatico: "AUTOMÁTICO",
    manual: "MANUAL",
    sys_link: "SYS LINK",
    identificandose: "Identificándose...",
    cambiar_operario: "Cambiar Operario",
    autorizado: "Autorizado",
    ajustes_sistema: "Ajustes del sistema",
    finaliza_secuencia_operario: "Finaliza o aborta la secuencia actual para cambiar operario",
    cod: "CÓD.",
    log_alarmas: "LOG. ALARMAS",

    // Left Panel (Datos ERP)
    datos_erp: "DATOS ERP",
    esquema_ng6of1: "Esquema NG6OF1",
    esperando_lectura: "Esperando lectura de bastidor para vincular datos",
    dat_sincronizado: "DAT sincronizado",
    dafeed_directo: "DAFEED en directo",
    identidad: "Identidad",
    parametros: "Parámetros",
    tolerancias: "Tolerancias",
    con_carga: "Con Carga",
    sin_carga: "Sin Carga",
    elevac: "ELEVAC.",
    descenso: "DESCENSO",
    sincroniza_dat: "Sincroniza el DAT para ver tiempos reales",
    bastidor: "BASTIDOR",
    modelo: "MODELO",
    mastil: "MÁSTIL",
    secuencia: "SECUENCIA",
    fec_montaje: "FEC. MONTAJE",
    maquina: "MÁQUINA",
    tonelaje: "TONELAJE",
    alt_max_interm: "ALT. MAX INTERM.",
    peso_pruebas: "PESO PRUEBAS",
    capac_interm_1: "CAPAC. INTERM. 1",
    capac_interm_2: "CAPAC. INTERM. 2",
    capac_interm_3: "CAPAC. INTERM. 3",

    // Telemetry HUD
    laser_sensor: "Laser Sensor (Y)",
    cycle_time: "Cycle Time",
    en_espera: "EN ESPERA",

    // Login Operario
    introduzca_codigo: "Introduzca su código o apellidos",
    ej_operario: "Ej. 00000764 o URBICAIN",
    operario_no_encontrado: "Operario no encontrado",
    error_conexion_erp: "Error de conexión con el servidor ERP.",
    codigo_label: "CÓDIGO:",

    // Settings Modal
    preferencias_dispositivos: "Preferencias y Dispositivos",
    lector_qr: "Lector QR",
    tolerancia: "Tolerancia",
    prueba_5_min: "Prueba 5 Min",
    visor_3d: "Visor 3D",
    camara_3d: "Cámara 3D",
    camara_basler: "Cámara Basler",
    lenguajes: "Lenguajes",
    configurar_lector_qr: "Configurar Lector QR",
    actualizar_puertos: "Puertos COM",
    tipo_conexion: "Tipo de Conexión",
    usb_teclado: "USB (Teclado)",
    serial_com: "Serial (COM)",
    puerto_com: "Puerto COM",
    baud_rate: "Baud Rate",
    test_conexion: "Test Conexión",
    leer_datos: "Leer Datos",
    probando: "Probando...",
    leyendo: "Leyendo...",
    resultado_lectura: "Resultado de Lectura",
    lector_usb_desc: "Tu lector QR está conectado por USB y actuando como un teclado convencional (emulación de teclado). Haz clic en el recuadro de abajo y escanea un código para probarlo:",
    haz_clic_escanear: "Haz clic aquí y escanea un código...",
    lectura_vacia: "Lectura vacía",
    no_detectado: "No detectado",
    tolerancia_multiload: "Tolerancia (Multiload)",
    tolerancia_desc: "Configure los márgenes de tolerancia para la colocación de la pegatina en la etapa de Multiload. El sistema indicará posición correcta si la altura del láser se encuentra dentro de estos límites respecto a la ALTURA MAX del ERP.",
    tolerancia_positiva: "Tolerancia en Positivo (+mm)",
    tolerancia_negativa: "Tolerancia en Negativo (-mm)",
    cota_inicial_pruebas: "Cota Inicial Pruebas (mm)",
    cota_inicial_desc: "Configure la cota de inicio estandarizada para las pruebas de elevación. Normalmente 1500 mm.",
    prueba_5_minutos_titulo: "Prueba 5 Minutos (Mx / XL)",
    prueba_5_minutos_desc: "Configure la duración de la prueba de estabilidad en carga y la tolerancia máxima permitida de caída (variación en milímetros) respecto a la altura inicial.",
    duracion_segundos: "Duración (segundos)",
    tolerancia_caida: "Tolerancia de caída (mm)",
    visor_3d_titulo: "Visor 3D (OBJ/MTL)",
    subir_obj: "Subir .OBJ",
    subir_mtl: "Subir .MTL",
    ningun_archivo: "Ningún archivo seleccionado",
    opcional_materiales: "Opcional (Materiales)",
    camara_debug_titulo: "Cámara Recreación (Debug)",
    camara_debug_desc: "Mueve la cámara en el entorno 3D a la posición deseada, abre este menú y pulsa el botón para obtener las coordenadas exactas. Así podrás compartirlas para fijar la posición.",
    obtener_posicion: "Obtener Posición Actual",
    mover_camara_aviso: "Mueve un poco la cámara en la pantalla principal primero para registrar sus coordenadas.",
    config_basler_titulo: "Configuración Cámara Basler",
    config_basler_desc: "Configure la dirección IP de la cámara industrial Basler. Si la deja en blanco, el sistema intentará autodetectar la primera cámara disponible en la red.",
    ip_opcional: "Dirección IP (Opcional)",
    diagnostico_camara: "Diagnóstico de Cámara",
    diagnosticando: "Diagnosticando...",
    basler_error_captura: "Cámara conectada, pero error al capturar imagen.",
    basler_no_conectada: "Cámara no conectada",
    preview_basler: "PREVIEW BASLER",

    // Nueva Pestaña Lenguajes
    configurar_idioma: "Configuración de Idioma",
    seleccione_idioma: "Seleccione el idioma de la interfaz de la aplicación:",
    castellano_op: "Castellano (Español)",
    ingles_op: "Inglés (English)",
    japones_op: "Japonés (日本語)",
    idioma_nota: "Nota: Al cambiar el idioma, las etiquetas y descripciones del HMI se actualizarán de forma inmediata.",

    // Overlays e indicaciones de secuencia en App.jsx
    altura_actual: "ALTURA ACTUAL",
    objetivo: "OBJETIVO",
    carretilla_en_posicion: "CARRETILLA EN POSICIÓN. PUEDE COLOCAR PEGATINA.",
    puede_colocar_pegatina: "PUEDE COLOCAR PEGATINA.",
    carretilla_fuera_tolerancia: "CARRETILLA FUERA DE TOLERANCIA.",

    // App.jsx overlays / banners / modals / alarms
    limite_inicio: "LÍMITE INICIO:",
    carretilla_demasiado_alta: "¡CARRETILLA DEMASIADO ALTA!",
    baje_por_debajo_de: "Baje por debajo de {cota} mm para poder iniciar.",
    esperando_inicio: "ESPERANDO INICIO...",
    ascenso_en_curso: "ASCENSO EN CURSO",
    estabilizando_tiempo: "ESTABILIZANDO ({tiempo}s)",
    descenso_en_curso: "DESCENSO EN CURSO",
    prueba_completada: "PRUEBA COMPLETADA",
    prueba_fallida: "PRUEBA FALLIDA",
    ascenso_up: "↑ Ascenso",
    avg_velocidad: "AVG: {velocidad} mm/s",
    estabilizando_label: "Estabilizando",
    descenso_down: "↓ Descenso",
    test_sin_carga: "TEST SIN CARGA",
    test_con_carga: "TEST CON CARGA",
    estabilidad_5m_hud: "ESTABILIDAD 5 MINUTOS",
    prueba_metros: "PRUEBA {metros}m",
    caida_maxima_value: "CAÍDA MÁXIMA {mm}mm",
    test_estabilidad_5min: "TEST DE ESTABILIDAD (5 MIN)",
    carretilla_demasiado_baja: "¡CARRETILLA DEMASIADO BAJA!",
    eleve_por_encima_de: "Eleve por encima de {cota} mm para comenzar a estabilizar.",
    estabilizando_dots: "ESTABILIZANDO...",
    prueba_en_curso: "PRUEBA EN CURSO",
    prueba_superada: "PRUEBA SUPERADA",
    alarmas_activas: "Alarmas Activas",
    reset_alarmas: "Reset Alarmas",
    no_alarmas_activas: "No hay alarmas activas en este momento.",
    log_alarmas: "Log_Alarms",
    borrar_historico: "Borrar Histórico",
    exportar_xlsx: "Exportar .xlsx",
    no_alarmas_historico: "No hay alarmas registradas en el histórico.",
    fecha_hora: "Fecha y Hora",
    alarma_advertencia: "Alarma / Advertencia",
    descripcion: "Descripción",
    duracion: "Duración",
    advertencia_label: "ADVERTENCIA",
    alarma_label: "ALARMA",
    alarma_activa: "Activa",
    vallas_no_posicion: "VALLAS NO EN POSICIÓN",
    peligro_jaula_no_segura: "PELIGRO: LA JAULA NO ES SEGURA",
    atencion_vallas_abajo: "¡¡ ATENCIÓN VALLAS ABAJO !!",
    subirlas_al_finalizar: "SUBIRLAS AL FINALIZAR LA PRUEBA",
    control_carga: "Control de Carga",
    peso_erp: "PESO ERP",
    peso_prueba: "PESO PRUEBA",
    carga_actual: "CARGA ACTUAL",
    pallets_multi: "({pallets} pallets × 250kg)",
    estado_prueba: "Estado Prueba",
    esperando: "ESPERANDO...",
    espera_cota_subir: "ESPERA {cota} mm ↑",
    ascenso_activo: "ASCENSO ACTIVO",
    descenso_activo: "DESCENSO ACTIVO",
    prueba_ok: "PRUEBA OK ✓",
    prueba_nok: "PRUEBA NOK ✗",
    espera_para_descender: "⟱ ESPERA PARA DESCENDER",
    midiendo: "● MIDIENDO",
    erp_objetivo: "ERP OBJETIVO:",
    prueba_elevacion_label: "Prueba de Elevación",
    elevacion_finalizada: "ELEVACIÓN FINALIZADA",
    inicio_descenso_en: "Inicio del descenso en",
    segundo: "segundo",
    segundos: "segundos",
    inicie_descenso: "↓ Inicie Descenso ↓",
    confirmando_senal_parada: "Confirmando señal de parada...",
    carga_cota_incorrecta: "CARGA O COTA INCORRECTA",
    condiciones_no_cumplidas: "Condiciones no cumplidas",
    carga_no_corresponde: "La carga no corresponde con lo que propone el ERP. Revise los pallets de hierro y madera.",
    validacion_carga: "VALIDACIÓN DE CARGA",
    movimiento_incompleto: "MOVIMIENTO INCOMPLETO",
    ascenso_incompleto: "Ascenso Incompleto",
    descenso_incompleto: "Descenso Incompleto",
    ascenso_incompleto_desc: "La carretilla no alcanzó la altura máxima requerida. La prueba ha sido cancelada.",
    descenso_incompleto_desc: "La carretilla no completó el descenso hasta la posición inicial. La prueba ha sido cancelada.",
    detenido_sin_completar: "Detenido sin completar el recorrido (timeout 2s)",
    caida_excesiva: "CAÍDA EXCESIVA",
    repetir_prueba: "¿Repetir la prueba?",
    caida_excesiva_desc: "La altura ha descendido por debajo de la tolerancia configurada ({subtitle}).",
    resultado_fuera_tolerancia: "RESULTADO FUERA DE TOLERANCIA",
    tiempos_no_cumplen_erp: "Los tiempos registrados no cumplen las tolerancias del ERP.",
    pulsador_fisico_detectado: "Pulsador físico detectado...",
    si_repetir: "SÍ — Repetir",
    click_iniciar: "Click para iniciar",
    no_continuar: "NO — Continuar",
    click_continuar: "Click para continuar",
    iniciar_secuencia_sim: "Iniciar\nSecuencia",
    pegatina_colocada_sim: "Pegatina\nColocada",
    abortar_secuencia_sim: "Abortar\nSecuencia",
    jaula_label: "Jaula",
    subir_vallas_title: "Subir Vallas",
    bajar_vallas_title: "Bajar Vallas",
    pallets_sim_label: "Pallets Sim.",
    no_iniciar_alarmas_criticas: "No se puede iniciar la secuencia: Hay alarmas críticas activas.",
    error_visor_3d: "Error en el visor 3D",
    error_visor_3d_desc: "El motor 3D ha fallado. Recargue la página para restaurar la visualización.",
    recargar_btn: "🔄 Recargar",
    identificacion: "Identificación",
    operario_codigo_apellidos: "Introduzca su código o apellidos",
    confirmar_borrar_historico: "¿Seguro que deseas borrar todo el histórico de alarmas de la base de datos?",
    no_iniciar_modo_manual: "No se puede iniciar la secuencia: La máquina está en modo MANUAL.",
    espera_arriba: "ESPERA ARRIBA",
    // PLC Modal & PLC variables
    Ob_Poner_Pegatina: "Poner Pegatina",
    Ob_Iniciar_Secuencia: "Iniciar Secuencia",
    Ob_Abortar_Secuencia: "Abortar Secuencia",
    Ib_LUZ_Pulsador_1: "Luz Pulsador 1",
    Ib_LUZ_Pulsador_2: "Luz Pulsador 2",
    Ib_LUZ_VERDE: "Baliza Verde",
    Ib_LUZ_AZUL: "Baliza Azul",
    Ib_LUZ_ROJA: "Baliza Roja",
    Ib_EV_VALLA_REPOSO: "Electro Válvula Reposo",
    Ib_EV_VALLA_TRABAJO: "Electro Válvula Trabajo",
    OW_Numero_Pallets: "Número de Pallets",
    Ob_Bit_VIDA_PLC_APP: "Bit Vida (PLC → APP)",
    Ib_Bit_VIDA_APP_PLC: "Bit Vida (APP → PLC)",
    OR_Altura_Carretilla: "Láser Altura Elevación",
    Ob_Trabajo_Cilindro_Valla_1: "Detector Cilindro Valla 1 Trabajo",
    Ob_Trabajo_Cilindro_Valla_2: "Detector Cilindro Valla 2 Trabajo",
    Ob_Reposo_Cilindro_Valla_1: "Detector Cilindro Valla Reposo",
    Ob_Estado_Automatico: "Estado Automático (Auto/Manual)",
    OW_Tiempo_Elevacion: "Tiempo Elevación",
    OW_Tiempo_Descenso: "Tiempo Descenso",
    inicia_temporizador_ascenso: "Inicia Temp Ascenso",
    inicia_temporizador_descenso: "Inicia Temp Descenso",
    altura_relativa: "Altura Relativa (1m o 2m)",
    consigna_posicion_altura: "Consigna Posición Altura (Cota Inicial)",
    Ob_Ready_Temporizador: "Temporizadores Ready (PLC)",
    Ib_Restart_Temporizador: "Restart Temporizador (HMI)",
    dispositivos_encontrados: "Dispositivos Encontrados",
    data_blocks_disponibles: "Data Blocks Disponibles",
    error_conexion: "Error de Conexión",
    no_resultados: "No se encontraron resultados.",
    diag_config_plc: "Diagnóstico & Configuración PLC",
    monitor_control_opcua: "Monitorización, Control y OPC UA",
    modo_simulacion_btn: "Modo Simulación",
    conectado_plc_btn: "Conectado a PLC",
    configuracion_opc_ua: "Configuración OPC UA",
    ip_servidor_plc: "IP del Servidor (PLC)",
    buscando_dots: "Buscando...",
    escanear_red: "Escanear Red",
    puerto_opc_ua: "Puerto OPC UA",
    nombre_db: "Nombre DB",
    consultando_dots: "Consultando...",
    buscar_en_plc: "Buscar en PLC",
    velocidad_escaneo_hz: "Velocidad de Escaneo (Hz)",
    namespace_ns: "Namespace (ns)",
    guardar_configuracion: "Guardar Configuración",
    desconectar_simulacion: "Desconectar (Modo Simulación)",
    config_plc_nota: "Esta configuración indica a la aplicación Python dónde encontrar el Servidor OPC UA y en qué DB de Siemens se exponen las variables de la máquina.",
    opcua_conectado: "OPC UA Conectado",
    diagnosticando_conexion_dots: "Diagnosticando Conexión...",
    opcua_desconectado: "OPC UA Desconectado",
    tia_portal_cert_warn: "⚠️ Recuerda aprobar el certificado en TIA Portal (Security > Certificate manager) para permitir la conexión.",
    topologia_estado_conexion: "Topología y Estado de Conexión",
    hmi_app_label: "HMI App",
    opcua_connected_uppercase: "OPC UA CONECTADO",
    disconnected_uppercase: "DESCONECTADO",
    latencia: "Latencia",
    listado_variables_plc_db: "Listado de Variables del PLC (DB)",
    items_uppercase: "ITEMS",
    sin_variables_detectadas: "Sin variables detectadas.",
    verifique_conexion: "Verifique la conexión.",
    config_vars_asignar_plc: "Configuración de Variables — Asignar PLC a Proyecto",
    mapeadas_uppercase: "MAPEADAS",
    modo_sim_forzado_activado: "Modo Simulación: Forzado Activado",
    deshabilitar_forzado_manual: "Deshabilitar Forzado Manual",
    habilitar_forzado_manual: "Habilitar Forzado Manual",
    in_lectura_plc_app: "IN (Lectura PLC → APP)",
    direccion: "Dirección",
    proyecto: "Proyecto",
    plc_db: "PLC DB",
    valor: "Valor",
    no_vars_in_mapeadas: "No hay variables IN mapeadas.",
    out_escritura_app_plc: "OUT (Escritura APP → PLC)",
    forzar: "Forzar",
    no_vars_out_mapeadas: "No hay variables OUT mapeadas.",
    configuracion_alarmas: "Configuración de Alarmas",
    in_alarmas_lectura_plc_app: "IN ALARMAS (Lectura PLC → APP)",
    btn_anadir: "+ Añadir",
    tipologia: "Tipología",
    causa: "Causa",
    remedio: "Remedio",
    select_option: "-- Seleccionar --",
    no_alarmas_configuradas: "No hay alarmas configuradas.",
    out_alarmas_escritura_app_plc: "OUT ALARMAS (Escritura APP → PLC)",
    out_escritura_option: "OUT (Escritura)",
    nombre_accion_placeholder: "Nombre de la acción",
    // ERP Preview Card
    mastil_header: "MÁSTIL",
    mastil_ref: "Mástil REF",
    geometria: "Geometría",
    cargas_y_capacidades: "Cargas y Capacidades",
    tpo_con_carga: "Tpo Con Carga",
    tpo_sin_carga: "Tpo Sin Carga",
    elevacion_min: "Elevación mín",
    elevacion_max: "Elevación máx",
    descenso_min: "Descenso mín",
    descenso_max: "Descenso máx",
    cargar_secuencia_btn: "Cargar Secuencia",
    cargar_secuencia_display: "CARGAR SECUENCIA ({displayTime}s)",
    in_lectura_option: "IN (Lectura)",
    ninguna_option: "-- Ninguna --",
    sin_conexion_opcua: "Sin conexión OPC UA",
    ingrese_valor_para: "Ingrese valor para {varName}",
    fijar_btn: "Fijar",
    toggle_btn: "Toggle",
    no_comandos_out_alarmas: "No hay comandos OUT de alarma configurados.",
    protocolo_prueba: "Protocolo de Prueba",
    abortar: "Abortar",
    identificar_carretilla: "Identificar carretilla",
    escaner: "Escáner",
    erp_btn: "ERP",
    esperando_lectura_dots: "Esperando lectura…",
    escribe_bastidor: "Escribe el bastidor…",
    buscar_en_erp: "Buscar en ERP",
    escribe_bastidor_enter: "Escribe el número de bastidor y pulsa Enter",
    buscando_en_erp: "Buscando en ERP…",
    posicion_multiload: "Posición multiload",
    altura_max: "Altura máx",
    actual: "Actual",
    esperando_iniciar_secuencia: "ESPERANDO: Pulse INICIAR SECUENCIA",
    coloque_pegatina_desc: "Coloca la pegatina. El mástil debe estar en la altura correcta para confirmar.",
    animacion_palet_en_curso: "Animación de recogida del palet en curso...",
    altura_incorrecta_desc: "Altura incorrecta. Posiciona el mástil dentro del rango.",
    pegatina_posicionada: "Pegatina Posicionada",
    sin_multiload_omitido: "Altura máx = 0 → Sin multiload. Paso omitido.",
    pos_pegatina: "Pos. pegatina",
    test_sin_carga_prueba: "Test sin carga - PRUEBA",
    temporizadores_plc: "Temporizadores PLC",
    esperando_condiciones: "ESPERANDO CONDICIONES",
    ascenso_activo_status: "ASCENSO ACTIVO",
    esperando_arriba_status: "ESPERANDO ARRIBA",
    descenso_activo_status: "DESCENSO ACTIVO",
    elevacion_finalizada_status: "ELEVACIÓN FINALIZADA",
    prueba_nok_status: "PRUEBA NOK",
    ascenso_s: "Ascenso (s)",
    descenso_s: "Descenso (s)",
    baje_por_debajo_de_iniciar: "Baje por debajo de {cota} mm para iniciar",
    listo_para_iniciar: "Listo para iniciar",
    retira_carga_desc: "Retira la carga y ejecuta la prueba. La cámara registrará los tiempos de ciclo.",
    elevacion_finalizada_msg: "Elevación Finalizada",
    fallo_camara_sin_carga: "Fallo de prueba de cámara sin carga.",
    repetir_prueba_btn: "Repetir Prueba",
    continuar_btn: "Continuar",
    pendiente_paso_anterior: "Pendiente paso anterior",
    test_con_carga_prueba: "Test con carga - PRUEBA",
    esperando_ascenso_cota: "ESPERANDO ASCENSO (>{cota}M)",
    carga_carretilla_desc: "Carga la carretilla con la capacidad indicada ({peso} kg) y ejecuta la prueba. La cámara registrará los tiempos de ciclo.",
    animacion_palet_en_curso_load: "Animación de palet en curso...",
    fallo_camara_con_carga: "Fallo de prueba de cámara con carga.",
    prueba_5_minutos: "Prueba 5 minutos",
    altura_mastil: "Altura mástil",
    eleve_por_encima_de_cota: "Eleve por encima de {cota} mm",
    esperando_inicio_status: "ESPERANDO INICIO",
    esperando_altura_status: "ESPERANDO: ALTURA >{cota}M",
    estabilizando_3s_status: "ESTABILIZANDO (3s)...",
    prueba_en_curso_status: "PRUEBA EN CURSO",
    prueba_ok_status: "PRUEBA OK",
    verifique_carga_desc: "Verifique que la carga actual coincida con la requerida y eleve el mástil por encima de {cota} mm. La prueba comenzará automáticamente una vez estabilizado.",
    altura_inicial: "Altura inicial:",
    fallo_prueba_caida_excedida: "Fallo de prueba: variación de altura excedida.",
    no_es_mx_xl_omitido: "Modelo {modelo} → no es Mx/XL. Paso omitido.",
    prueba_5_minutos_superada: "Prueba de 5 minutos superada ✓",
    secuencia_completada: "Secuencia Completada",
    secuencia_completada_desc: "Log guardado automáticamente. Vuelva al origen. Precaución: Vallas en trabajo (Baliza Roja).",
    progreso: "Progreso",
    cancelar_prueba: "Cancelar prueba",
    secuencia_repetida: "Secuencia Repetida",
    secuencia_repetida_desc: "El bastidor {bastidor} ya fue probado. Selecciona qué etapas repetir (las no superadas se marcan por defecto).",
    paso_2_multiload: "Paso 2: Multiload",
    paso_3_sincarga: "Paso 3: Sin Carga",
    paso_4_concarga: "Paso 4: Con Carga",
    paso_5_prueba5m: "Paso 5: Prueba 5M",
    pulse_iniciar_secuencia_continuar: "Pulse INICIAR SECUENCIA para continuar",
    reiniciar_secuencia: "Reiniciar secuencia",
    baje_por_debajo_de_cota: "Baje por debajo de {cota} mm",
    restaurar_etapa: "Restaurar etapa",
    deshabilitar_etapa: "Deshabilitar etapa"
  },
  en: {
    // Generales
    cancelar: "Cancel",
    guardar: "Save",
    buscar: "Search",
    ok: "OK",
    si: "Yes",
    no: "No",
    estado: "Status",
    cargando: "Loading...",
    error: "Error",
    advertencia: "Warning",
    cerrar: "Close",

    // Header
    pruebas_elevacion: "ELEVATION TESTS",
    automatico: "AUTOMATIC",
    manual: "MANUAL",
    sys_link: "SYS LINK",
    identificandose: "Identifying...",
    cambiar_operario: "Change Operator",
    autorizado: "Authorized",
    ajustes_sistema: "System settings",
    finaliza_secuencia_operario: "Finish or abort the current sequence to change operator",
    cod: "COD.",
    log_alarmas: "ALARMS LOG",

    // Left Panel (Datos ERP)
    datos_erp: "ERP DATA",
    esquema_ng6of1: "Scheme NG6OF1",
    esperando_lectura: "Waiting for chassis reading to link data",
    dat_sincronizado: "DAT synchronized",
    dafeed_directo: "DAFEED live",
    identidad: "Identity",
    parametros: "Parameters",
    tolerancias: "Tolerances",
    con_carga: "With Load",
    sin_carga: "Without Load",
    elevac: "ELEV.",
    descenso: "DESCENT",
    sincroniza_dat: "Synchronize DAT to see actual times",
    bastidor: "CHASSIS",
    modelo: "MODEL",
    mastil: "MAST",
    secuencia: "SEQUENCE",
    fec_montaje: "ASSY. DATE",
    maquina: "MACHINE",
    tonelaje: "TONNAGE",
    alt_max_interm: "MAX INTERM. H.",
    peso_pruebas: "TEST WEIGHT",
    capac_interm_1: "INTERM. CAP. 1",
    capac_interm_2: "INTERM. CAP. 2",
    capac_interm_3: "INTERM. CAP. 3",

    // Telemetry HUD
    laser_sensor: "Laser Sensor (Y)",
    cycle_time: "Cycle Time",
    en_espera: "WAITING",

    // Login Operario
    introduzca_codigo: "Enter your code or last name",
    ej_operario: "E.g. 00000764 or URBICAIN",
    operario_no_encontrado: "Operator not found",
    error_conexion_erp: "Connection error with ERP server.",
    codigo_label: "CODE:",

    // Settings Modal
    preferencias_dispositivos: "Preferences & Devices",
    lector_qr: "QR Reader",
    tolerancia: "Tolerance",
    prueba_5_min: "5 Min Test",
    visor_3d: "3D Viewer",
    camara_3d: "3D Camera",
    camara_basler: "Basler Camera",
    lenguajes: "Languages",
    configurar_lector_qr: "Configure QR Reader",
    actualizar_puertos: "COM Ports",
    tipo_conexion: "Connection Type",
    usb_teclado: "USB (Keyboard)",
    serial_com: "Serial (COM)",
    puerto_com: "COM Port",
    baud_rate: "Baud Rate",
    test_conexion: "Connection Test",
    leer_datos: "Read Data",
    probando: "Testing...",
    leyendo: "Reading...",
    resultado_lectura: "Reading Result",
    lector_usb_desc: "Your QR reader is connected via USB and acting as a standard keyboard (keyboard emulation). Click in the box below and scan a code to test it:",
    haz_clic_escanear: "Click here and scan a code...",
    lectura_vacia: "Empty reading",
    no_detectado: "Not detected",
    tolerancia_multiload: "Tolerance (Multiload)",
    tolerancia_desc: "Configure the tolerance margins for placing the sticker in the Multiload stage. The system will indicate correct position if the laser height is within these limits relative to the ERP MAX HEIGHT.",
    tolerancia_positiva: "Positive Tolerance (+mm)",
    tolerancia_negativa: "Negative Tolerance (-mm)",
    cota_inicial_pruebas: "Initial Test Height (mm)",
    cota_inicial_desc: "Configure the standardized initial height for elevation tests. Typically 1500 mm.",
    prueba_5_minutos_titulo: "5 Minutes Test (Mx / XL)",
    prueba_5_minutos_desc: "Configure the stability test duration under load and the maximum allowed drop tolerance (variation in millimeters) relative to the initial height.",
    duracion_segundos: "Duration (seconds)",
    tolerancia_caida: "Drop Tolerance (mm)",
    visor_3d_titulo: "3D Viewer (OBJ/MTL)",
    subir_obj: "Upload .OBJ",
    subir_mtl: "Upload .MTL",
    ningun_archivo: "No file selected",
    opcional_materiales: "Optional (Materials)",
    camara_debug_titulo: "Recreation Camera (Debug)",
    camara_debug_desc: "Move the camera in the 3D environment to the desired position, open this menu and click the button to get the exact coordinates. This way you can share them to lock the position.",
    obtener_posicion: "Get Current Position",
    mover_camara_aviso: "Move the camera slightly in the main screen first to register its coordinates.",
    config_basler_titulo: "Basler Camera Configuration",
    config_basler_desc: "Configure the IP address of the Basler industrial camera. If left blank, the system will attempt to auto-detect the first available camera on the network.",
    ip_opcional: "IP Address (Optional)",
    diagnostico_camara: "Camera Diagnostics",
    diagnosticando: "Diagnosing...",
    basler_error_captura: "Camera connected, but error capturing image.",
    basler_no_conectada: "Camera not connected",
    preview_basler: "BASLER PREVIEW",

    // Nueva Pestaña Lenguajes
    configurar_idioma: "Language Settings",
    seleccione_idioma: "Select the interface language for the application:",
    castellano_op: "Spanish (Castellano)",
    ingles_op: "English (Inglés)",
    japones_op: "Japanese (Japonés)",
    idioma_nota: "Note: Changing the language will instantly update all HMI labels and descriptions.",

    // Overlays e indicaciones de secuencia en App.jsx
    altura_actual: "CURRENT HEIGHT",
    objetivo: "TARGET",
    carretilla_en_posicion: "FORKLIFT IN POSITION. CAN PLACE STICKER.",
    puede_colocar_pegatina: "STICKER CAN BE PLACED.",
    carretilla_fuera_tolerancia: "FORKLIFT OUT OF TOLERANCE.",

    // App.jsx overlays / banners / modals / alarms
    limite_inicio: "START LIMIT:",
    carretilla_demasiado_alta: "FORKLIFT TOO HIGH!",
    baje_por_debajo_de: "Lower below {cota} mm to start.",
    esperando_inicio: "WAITING TO START...",
    ascenso_en_curso: "LIFTING IN PROGRESS",
    estabilizando_tiempo: "STABILIZING ({tiempo}s)",
    descenso_en_curso: "LOWERING IN PROGRESS",
    prueba_completada: "TEST COMPLETED",
    prueba_fallida: "TEST FAILED",
    ascenso_up: "↑ Lift",
    avg_velocidad: "AVG: {velocidad} mm/s",
    estabilizando_label: "Stabilizing",
    descenso_down: "↓ Lower",
    test_sin_carga: "TEST WITHOUT LOAD",
    test_con_carga: "TEST WITH LOAD",
    estabilidad_5m_hud: "STABILITY 5 MINUTES",
    prueba_metros: "TEST {metros}m",
    caida_maxima_value: "MAXIMUM DROP {mm}mm",
    test_estabilidad_5min: "STABILITY TEST (5 MIN)",
    carretilla_demasiado_baja: "FORKLIFT TOO LOW!",
    eleve_por_encima_de: "Raise above {cota} mm to start stabilizing.",
    estabilizando_dots: "STABILIZING...",
    prueba_en_curso: "TEST IN PROGRESS",
    prueba_superada: "TEST PASSED",
    alarmas_activas: "Active Alarms",
    reset_alarmas: "Reset Alarms",
    no_alarmas_activas: "There are no active alarms at this time.",
    log_alarmas: "Log_Alarms",
    borrar_historico: "Clear Log",
    exportar_xlsx: "Export .xlsx",
    no_alarmas_historico: "No alarms registered in the log.",
    fecha_hora: "Date & Time",
    alarma_advertencia: "Alarm / Warning",
    descripcion: "Description",
    duracion: "Duration",
    advertencia_label: "WARNING",
    alarma_label: "ALARM",
    alarma_activa: "Active",
    vallas_no_posicion: "GATES NOT IN POSITION",
    peligro_jaula_no_segura: "DANGER: GAGE IS NOT SAFE",
    atencion_vallas_abajo: "!! WARNING GATES DOWN !!",
    subirlas_al_finalizar: "RAISE THEM WHEN TEST IS FINISHED",
    control_carga: "Load Control",
    peso_erp: "ERP WEIGHT",
    peso_prueba: "TEST WEIGHT",
    carga_actual: "CURRENT LOAD",
    pallets_multi: "({pallets} pallets × 250kg)",
    estado_prueba: "Test Status",
    esperando: "WAITING...",
    espera_cota_subir: "WAIT {cota} mm ↑",
    ascenso_activo: "LIFT ACTIVE",
    descenso_activo: "LOWER ACTIVE",
    prueba_ok: "TEST OK ✓",
    prueba_nok: "TEST NOK ✗",
    espera_para_descender: "⟱ WAIT TO DESCEND",
    midiendo: "● MEASURING",
    erp_objetivo: "ERP TARGET:",
    prueba_elevacion_label: "Elevation Test",
    elevacion_finalizada: "LIFT FINISHED",
    inicio_descenso_en: "Descent starts in",
    segundo: "second",
    segundos: "seconds",
    inicie_descenso: "↓ Start Descent ↓",
    confirmando_senal_parada: "Confirming stop signal...",
    carga_cota_incorrecta: "INCORRECT LOAD OR HEIGHT",
    condiciones_no_cumplidas: "Conditions not met",
    carga_no_corresponde: "The load does not match the ERP requirements. Check iron and wood pallets.",
    validacion_carga: "LOAD VALIDATION",
    movimiento_incompleto: "INCOMPLETE MOVEMENT",
    ascenso_incompleto: "Lift Incomplete",
    descenso_incompleto: "Descent Incomplete",
    ascenso_incompleto_desc: "The forklift did not reach the maximum required height. Test has been cancelled.",
    descenso_incompleto_desc: "The forklift did not complete descent to the initial position. Test has been cancelled.",
    detenido_sin_completar: "Stopped without completing movement (timeout 2s)",
    caida_excesiva: "EXCESSIVE DROP",
    repetir_prueba: "Repeat the test?",
    caida_excesiva_desc: "Height has dropped below configured tolerance ({subtitle}).",
    resultado_fuera_tolerancia: "RESULT OUT OF TOLERANCE",
    tiempos_no_cumplen_erp: "The recorded times do not meet ERP tolerances.",
    pulsador_fisico_detectado: "Physical button detected...",
    si_repetir: "YES — Repeat",
    click_iniciar: "Click to start",
    no_continuar: "NO — Continue",
    click_continuar: "Click to continue",
    iniciar_secuencia_sim: "Start\nSequence",
    pegatina_colocada_sim: "Sticker\nPlaced",
    abortar_secuencia_sim: "Abort\nSequence",
    jaula_label: "Cage",
    subir_vallas_title: "Raise Gates",
    bajar_vallas_title: "Lower Gates",
    pallets_sim_label: "Sim. Pallets",
    no_iniciar_alarmas_criticas: "Cannot start the sequence: There are active critical alarms.",
    error_visor_3d: "3D Viewer Error",
    error_visor_3d_desc: "The 3D engine has failed. Reload the page to restore the visualization.",
    recargar_btn: "🔄 Reload",
    identificacion: "Identification",
    operario_codigo_apellidos: "Enter your code or last name",
    confirmar_borrar_historico: "Are you sure you want to delete all the alarm history from the database?",
    no_iniciar_modo_manual: "Cannot start the sequence: The machine is in MANUAL mode.",
    espera_arriba: "WAIT TOP",
    // PLC Modal & PLC variables
    Ob_Poner_Pegatina: "Place Sticker",
    Ob_Iniciar_Secuencia: "Start Sequence",
    Ob_Abortar_Secuencia: "Abort Sequence",
    Ib_LUZ_Pulsador_1: "Button 1 Light",
    Ib_LUZ_Pulsador_2: "Button 2 Light",
    Ib_LUZ_VERDE: "Green Beacon",
    Ib_LUZ_AZUL: "Blue Beacon",
    Ib_LUZ_ROJA: "Red Beacon",
    Ib_EV_VALLA_REPOSO: "Solenoid Valve Repose",
    Ib_EV_VALLA_TRABAJO: "Solenoid Valve Work",
    OW_Numero_Pallets: "Number of Pallets",
    Ob_Bit_VIDA_PLC_APP: "Heartbeat (PLC → APP)",
    Ib_Bit_VIDA_APP_PLC: "Heartbeat (APP → PLC)",
    OR_Altura_Carretilla: "Laser Lift Height",
    Ob_Trabajo_Cilindro_Valla_1: "Cylinder Gate 1 Work Sensor",
    Ob_Trabajo_Cilindro_Valla_2: "Cylinder Gate 2 Work Sensor",
    Ob_Reposo_Cilindro_Valla_1: "Cylinder Gate Repose Sensor",
    Ob_Estado_Automatico: "Automatic State (Auto/Manual)",
    OW_Tiempo_Elevacion: "Elevation Time",
    OW_Tiempo_Descenso: "Descent Time",
    inicia_temporizador_ascenso: "Start Ascent Timer",
    inicia_temporizador_descenso: "Start Descent Timer",
    altura_relativa: "Relative Height (1m or 2m)",
    consigna_posicion_altura: "Consigna Position Height (Initial Level)",
    Ob_Ready_Temporizador: "Timers Ready (PLC)",
    Ib_Restart_Temporizador: "Restart Timer (HMI)",
    dispositivos_encontrados: "Devices Found",
    data_blocks_disponibles: "Available Data Blocks",
    error_conexion: "Connection Error",
    no_resultados: "No results found.",
    diag_config_plc: "PLC Diagnosis & Configuration",
    monitor_control_opcua: "Monitoring, Control & OPC UA",
    modo_simulacion_btn: "Simulation Mode",
    conectado_plc_btn: "Connected to PLC",
    configuracion_opc_ua: "OPC UA Configuration",
    ip_servidor_plc: "Server IP (PLC)",
    buscando_dots: "Searching...",
    escanear_red: "Scan Network",
    puerto_opc_ua: "OPC UA Port",
    nombre_db: "DB Name",
    consultando_dots: "Querying...",
    buscar_en_plc: "Find in PLC",
    velocidad_escaneo_hz: "Scan Rate (Hz)",
    namespace_ns: "Namespace (ns)",
    guardar_configuracion: "Save Configuration",
    desconectar_simulacion: "Disconnect (Simulation Mode)",
    config_plc_nota: "This configuration tells the Python application where to find the OPC UA Server and which Siemens DB exposes the machine variables.",
    opcua_conectado: "OPC UA Connected",
    diagnosticando_conexion_dots: "Diagnosing Connection...",
    opcua_desconectado: "OPC UA Disconnected",
    tia_portal_cert_warn: "⚠️ Remember to approve the certificate in TIA Portal (Security > Certificate manager) to allow connection.",
    topologia_estado_conexion: "Topology & Connection Status",
    hmi_app_label: "HMI App",
    opcua_connected_uppercase: "OPC UA CONNECTED",
    disconnected_uppercase: "DISCONNECTED",
    latencia: "Latency",
    listado_variables_plc_db: "PLC Variables List (DB)",
    items_uppercase: "ITEMS",
    sin_variables_detectadas: "No variables detected.",
    verifique_conexion: "Verify connection.",
    config_vars_asignar_plc: "Variable Configuration — Map PLC to Project",
    mapeadas_uppercase: "MAPPED",
    modo_sim_forzado_activado: "Simulation Mode: Force Enabled",
    deshabilitar_forzado_manual: "Disable Manual Override",
    habilitar_forzado_manual: "Enable Manual Override",
    in_lectura_plc_app: "IN (PLC Read → APP)",
    direccion: "Direction",
    proyecto: "Project",
    plc_db: "PLC DB",
    valor: "Value",
    no_vars_in_mapeadas: "No mapped IN variables.",
    out_escritura_app_plc: "OUT (APP Write → PLC)",
    forzar: "Force",
    no_vars_out_mapeadas: "No mapped OUT variables.",
    configuracion_alarmas: "Alarms Configuration",
    in_alarmas_lectura_plc_app: "IN ALARMS (PLC Read → APP)",
    btn_anadir: "+ Add",
    tipologia: "Typology",
    causa: "Cause",
    remedio: "Remedy",
    select_option: "-- Select --",
    no_alarmas_configuradas: "No configured alarms.",
    out_alarmas_escritura_app_plc: "OUT ALARMS (APP Write → PLC)",
    out_escritura_option: "OUT (Write)",
    nombre_accion_placeholder: "Action Name",
    // ERP Preview Card
    mastil_header: "MAST",
    mastil_ref: "Mast REF",
    geometria: "Geometry",
    cargas_y_capacidades: "Loads & Capacities",
    tpo_con_carga: "Time With Load",
    tpo_sin_carga: "Time Without Load",
    elevacion_min: "Min Elevation",
    elevacion_max: "Max Elevation",
    descenso_min: "Min Descent",
    descenso_max: "Max Descent",
    cargar_secuencia_btn: "Load Sequence",
    cargar_secuencia_display: "LOAD SEQUENCE ({displayTime}s)",
    in_lectura_option: "IN (Read)",
    ninguna_option: "-- None --",
    sin_conexion_opcua: "No OPC UA connection",
    ingrese_valor_para: "Enter value for {varName}",
    fijar_btn: "Set",
    toggle_btn: "Toggle",
    no_comandos_out_alarmas: "No configured alarm OUT commands.",
    protocolo_prueba: "Test Protocol",
    abortar: "Abort",
    identificar_carretilla: "Identify forklift",
    escaner: "Scanner",
    erp_btn: "ERP",
    esperando_lectura_dots: "Waiting for scan…",
    escribe_bastidor: "Enter chassis number…",
    buscar_en_erp: "Search in ERP",
    escribe_bastidor_enter: "Type the chassis number and press Enter",
    buscando_en_erp: "Searching in ERP…",
    posicion_multiload: "Multiload Position",
    altura_max: "Max Height",
    actual: "Actual",
    esperando_iniciar_secuencia: "WAITING: Press START SEQUENCE",
    coloque_pegatina_desc: "Place the sticker. The mast must be at the correct height to confirm.",
    animacion_palet_en_curso: "Pallet pickup animation in progress...",
    altura_incorrecta_desc: "Incorrect height. Position the mast within range.",
    pegatina_posicionada: "Sticker Positioned",
    sin_multiload_omitido: "Max Height = 0 → No multiload. Step skipped.",
    pos_pegatina: "Sticker pos.",
    test_sin_carga_prueba: "No load test - TEST",
    temporizadores_plc: "PLC Timers",
    esperando_condiciones: "WAITING FOR CONDITIONS",
    ascenso_activo_status: "LIFT ACTIVE",
    esperando_arriba_status: "WAITING TOP",
    descenso_activo_status: "LOWER ACTIVE",
    elevacion_finalizada_status: "LIFT COMPLETED",
    prueba_nok_status: "TEST NOK",
    ascenso_s: "Lift (s)",
    descenso_s: "Lower (s)",
    baje_por_debajo_de_iniciar: "Lower below {cota} mm to start",
    listo_para_iniciar: "Ready to start",
    retira_carga_desc: "Remove the load and run the test. The camera will record the cycle times.",
    elevacion_finalizada_msg: "Elevation Completed",
    fallo_camara_sin_carga: "Camera test failure without load.",
    repetir_prueba_btn: "Repeat Test",
    continuar_btn: "Continue",
    pendiente_paso_anterior: "Pending previous step",
    test_con_carga_prueba: "Load test - TEST",
    esperando_ascenso_cota: "WAITING FOR LIFT (>{cota}M)",
    carga_carretilla_desc: "Load the truck with the indicated capacity ({peso} kg) and run the test. The camera will record the cycle times.",
    animacion_palet_en_curso_load: "Pallet animation in progress...",
    fallo_camara_con_carga: "Camera test failure under load.",
    prueba_5_minutos: "5 minutes test",
    altura_mastil: "Mast height",
    eleve_por_encima_de_cota: "Raise above {cota} mm",
    esperando_inicio_status: "WAITING FOR START",
    esperando_altura_status: "WAITING: HEIGHT >{cota}M",
    estabilizando_3s_status: "STABILIZING (3s)...",
    prueba_en_curso_status: "TEST IN PROGRESS",
    prueba_ok_status: "TEST OK",
    verifique_carga_desc: "Verify that current load matches requirements and raise the mast above {cota} mm. The test will start automatically once stabilized.",
    altura_inicial: "Initial height:",
    fallo_prueba_caida_excedida: "Test failure: height variation exceeded.",
    no_es_mx_xl_omitido: "Model {modelo} → not Mx/XL. Step skipped.",
    prueba_5_minutos_superada: "5 minutes test passed ✓",
    secuencia_completada: "Sequence Completed",
    secuencia_completada_desc: "Log saved automatically. Return to origin. Caution: Gates in operation (Red Beacon).",
    progreso: "Progress",
    cancelar_prueba: "Cancel test",
    secuencia_repetida: "Repeated Sequence",
    secuencia_repetida_desc: "Chassis {bastidor} was already tested. Select which steps to repeat (failed steps are selected by default).",
    paso_2_multiload: "Step 2: Multiload",
    paso_3_sincarga: "Step 3: No Load",
    paso_4_concarga: "Step 4: With Load",
    paso_5_prueba5m: "Step 5: 5M Test",
    pulse_iniciar_secuencia_continuar: "Press START SEQUENCE to continue",
    reiniciar_secuencia: "Restart sequence",
    baje_por_debajo_de_cota: "Lower below {cota} mm",
    restaurar_etapa: "Restore step",
    deshabilitar_etapa: "Disable step"
  },
  ja: {
    // Generales
    cancelar: "キャンセル / CANCEL",
    guardar: "保存 / SAVE",
    buscar: "検索 / SEARCH",
    ok: "確定 / OK",
    si: "はい / YES",
    no: "いいえ / NO",
    estado: "状態 / STATUS",
    cargando: "ロード中... / LOADING...",
    error: "エラー / ERROR",
    advertencia: "警告 / WARNING",
    cerrar: "閉じる / CLOSE",

    // Header
    pruebas_elevacion: "昇降テスト / ELEVATION TESTS",
    automatico: "自動 / AUTOMATIC",
    manual: "手動 / MANUAL",
    sys_link: "システムリンク / SYS LINK",
    identificandose: "認証中... / IDENTIFYING...",
    cambiar_operario: "オペレーター変更 / CHANGE OPERATOR",
    autorizado: "認可済 / AUTHORIZED",
    ajustes_sistema: "システム設定 / SYSTEM SETTINGS",
    finaliza_secuencia_operario: "オペレーターを変更するには現在のシーケンスを終了または中止してください / FINISH OR ABORT THE CURRENT SEQUENCE TO CHANGE OPERATOR",
    cod: "コード / CODE",
    log_alarmas: "アラーム履歴 / ALARMS LOG",

    // Left Panel (Datos ERP)
    datos_erp: "ERPデータ / ERP DATA",
    esquema_ng6of1: "NG6OF1 スキーム / SCHEME NG6OF1",
    esperando_lectura: "データ連携のため車台読み取り待ち / WAITING FOR CHASSIS READING TO LINK DATA",
    dat_sincronizado: "DAT同期済 / DAT SYNCHRONIZED",
    dafeed_directo: "DAFEEDライブ / DAFEED LIVE",
    identidad: "識別情報 / IDENTITY",
    parametros: "パラメーター / PARAMETERS",
    tolerancias: "公差範囲 / TOLERANCES",
    con_carga: "荷重あり / WITH LOAD",
    sin_carga: "荷重なし / WITHOUT LOAD",
    elevac: "上昇 / ELEVATION",
    descenso: "下降 / DESCENT",
    sincroniza_dat: "実時間表示にはDATを同期してください / SYNCHRONIZE DAT TO SEE ACTUAL TIMES",
    bastidor: "車台番号 / CHASSIS",
    modelo: "モデル / MODEL",
    mastil: "マスト / MAST",
    secuencia: "シーケンス / SEQUENCE",
    fec_montaje: "組立日 / ASSY. DATE",
    maquina: "マシン / MACHINE",
    tonelaje: "トン数 / TONNAGE",
    alt_max_interm: "最大中間高 / MAX INTERM. H.",
    peso_pruebas: "テスト重量 / TEST WEIGHT",
    capac_interm_1: "中間容量 1 / INTERM. CAP. 1",
    capac_interm_2: "中間容量 2 / INTERM. CAP. 2",
    capac_interm_3: "中間容量 3 / INTERM. CAP. 3",

    // Telemetry HUD
    laser_sensor: "レーザーセンサー (Y) / LASER SENSOR (Y)",
    cycle_time: "サイクルタイム / CYCLE TIME",
    en_espera: "待機中 / WAITING",

    // Login Operario
    introduzca_codigo: "コードまたは姓を入力してください / ENTER YOUR CODE OR LAST NAME",
    ej_operario: "例: 00000764 または URBICAIN / E.G. 00000764 OR URBICAIN",
    operario_no_encontrado: "オペレーターが見つかりません / OPERATOR NOT FOUND",
    error_conexion_erp: "ERPサーバーとの接続エラー / CONNECTION ERROR WITH ERP SERVER.",
    codigo_label: "コード: / CODE:",

    // Settings Modal
    preferencias_dispositivos: "環境設定とデバイス / PREFERENCES & DEVICES",
    lector_qr: "QRリーダー / QR READER",
    tolerancia: "公差設定 / TOLERANCE",
    prueba_5_min: "5分間テスト / 5 MIN TEST",
    visor_3d: "3Dビューア / 3D VIEWER",
    camara_3d: "3Dカメラ / 3D CAMERA",
    camara_basler: "Baslerカメラ / BASLER CAMERA",
    lenguajes: "言語設定 / LANGUAGES",
    configurar_lector_qr: "QRリーダー設定 / CONFIGURE QR READER",
    actualizar_puertos: "COMポート / COM PORTS",
    tipo_conexion: "接続タイプ / CONNECTION TYPE",
    usb_teclado: "USB (キーボード) / USB (KEYBOARD)",
    serial_com: "シリアル (COM) / SERIAL (COM)",
    puerto_com: "COMポート / COM PORT",
    baud_rate: "ボーレート / BAUD RATE",
    test_conexion: "接続テスト / CONNECTION TEST",
    leer_datos: "データ読み取り / READ DATA",
    probando: "テスト中... / TESTING...",
    leyendo: "読み取り中... / READING...",
    resultado_lectura: "読み取り結果 / READING RESULT",
    lector_usb_desc: "QRリーダーはUSB経由で接続され、キーボードエミュレーションとして動作します。下のボックスをクリックしてスキャンテストを行ってください / Your QR reader is connected via USB and acting as a standard keyboard. Click below and scan a code to test it:",
    haz_clic_escanear: "ここをクリックしてスキャン... / CLICK HERE AND SCAN A CODE...",
    lectura_vacia: "空の読み取り / EMPTY READING",
    no_detectado: "検出なし / NOT DETECTED",
    tolerancia_multiload: "マルチロード公差 / TOLERANCE (MULTILOAD)",
    tolerancia_desc: "マルチロード工程でのステッカー貼付公差を設定します。レーザー測定高さが目標値の公差内にあるときに正しい位置として表示されます / Configure tolerance margins for placing the sticker in the Multiload stage. Displays correct position when height is within these limits relative to ERP height.",
    tolerancia_positiva: "正の公差 (+mm) / POSITIVE TOLERANCE (+MM)",
    tolerancia_negativa: "負の公差 (-mm) / NEGATIVE TOLERANCE (-MM)",
    cota_inicial_pruebas: "テスト初期高さ (mm) / INITIAL TEST HEIGHT (MM)",
    cota_inicial_desc: "昇降テストの標準初期高さを設定します。通常は1500 mmです / Configure standardized initial height for elevation tests. Typically 1500 mm.",
    prueba_5_minutos_titulo: "5分間テスト (Mx / XL) / 5 MINUTES TEST (MX / XL)",
    prueba_5_minutos_desc: "荷重をかけた状態での安定性テスト時間と、初期高さからの最大許容降下公差を設定します / Configure stability test duration under load and maximum allowed drop tolerance relative to initial height.",
    duracion_segundos: "期間 (秒) / DURATION (SECONDS)",
    tolerancia_caida: "降下公差 (mm) / DROP TOLERANCE (MM)",
    visor_3d_titulo: "3Dビューア (OBJ/MTL) / 3D VIEWER (OBJ/MTL)",
    subir_obj: ".OBJをアップロード / UPLOAD .OBJ",
    subir_mtl: ".MTLをアップロード / UPLOAD .MTL",
    ningun_archivo: "ファイル未選択 / NO FILE SELECTED",
    opcional_materiales: "オプション (素材) / OPTIONAL (MATERIALS)",
    camara_debug_titulo: "再現カメラ (デバッグ) / RECREATION CAMERA (DEBUG)",
    camara_debug_desc: "3Dカメラを目的の位置へ移動後、このメニューで現在の座標を取得し、それを共有して位置を固定できます / Move the camera in the 3D environment to the desired position, open this menu and click the button to get the coordinates.",
    obtener_posicion: "現在位置の取得 / GET CURRENT POSITION",
    mover_camara_aviso: "まずメイン画面でカメラを少し動かして位置を記録してください / Move the camera in the main screen first to register coordinates.",
    config_basler_titulo: "Baslerカメラ設定 / BASLER CAMERA CONFIGURATION",
    config_basler_desc: "Basler産業用カメラのIPアドレスを設定します。空欄の場合、ネットワーク上の最初のカメラを自動検出します / Configure the IP address of the Basler camera. If empty, auto-detects first available camera.",
    ip_opcional: "IPアドレス (任意) / IP ADDRESS (OPTIONAL)",
    diagnostico_camara: "カメラ診断 / CAMERA DIAGNOSTICS",
    diagnosticando: "診断中... / DIAGNOSING...",
    basler_error_captura: "接続されましたが、画像取得に失敗しました / Camera connected, but error capturing image.",
    basler_no_conectada: "カメラ未接続 / CAMERA NOT CONNECTED",
    preview_basler: "プレビュー / BASLER PREVIEW",

    // Nueva Pestaña Lenguajes
    configurar_idioma: "言語設定 / LANGUAGE SETTINGS",
    seleccione_idioma: "アプリケーションの表示言語を選択してください / SELECT THE INTERFACE LANGUAGE FOR THE APPLICATION:",
    castellano_op: "スペイン語 (Castellano)",
    ingles_op: "英語 (English)",
    japones_op: "日本語 (日本語 - Dual)",
    idioma_nota: "注意: 言語を変更すると、HMIのラベルと説明文が直ちに更新されます / Note: Changing the language will instantly update all HMI labels.",

    // Overlays e indicaciones de secuencia en App.jsx
    altura_actual: "現在高さ / CURRENT HEIGHT",
    objetivo: "目標値 / TARGET",
    carretilla_en_posicion: "フォークリフト位置正常。ステッカー貼付可能 / FORKLIFT IN POSITION. CAN PLACE STICKER.",
    puede_colocar_pegatina: "ステッカー貼付可能 / STICKER CAN BE PLACED.",
    carretilla_fuera_tolerancia: "フォークリフト公差外 / FORKLIFT OUT OF TOLERANCE.",

    // App.jsx overlays / banners / modals / alarms
    limite_inicio: "開始制限 / START LIMIT:",
    carretilla_demasiado_alta: "フォークリフトが高すぎます / FORKLIFT TOO HIGH!",
    baje_por_debajo_de: "開始するには {cota} mm 未満に下げてください / Lower below {cota} mm to start.",
    esperando_inicio: "開始待ち... / WAITING TO START...",
    ascenso_en_curso: "上昇中 / LIFTING IN PROGRESS",
    estabilizando_tiempo: "安定化中 ({tiempo}秒) / STABILIZING ({tiempo}S)",
    descenso_en_curso: "下降中 / LOWERING IN PROGRESS",
    prueba_completada: "テスト完了 / TEST COMPLETED",
    prueba_fallida: "テスト失敗 / TEST FAILED",
    ascenso_up: "↑ 上昇 / Lift",
    avg_velocidad: "平均速度: {velocidad} mm/s / AVG: {velocidad} MM/S",
    estabilizando_label: "安定化中 / Stabilizing",
    descenso_down: "↓ 下降 / Lower",
    test_sin_carga: "無荷重テスト / TEST WITHOUT LOAD",
    test_con_carga: "荷重テスト / TEST WITH LOAD",
    estabilidad_5m_hud: "5分間安定性テスト / STABILITY 5 MINUTES",
    prueba_metros: "テスト {metros}m / TEST {metros}m",
    caida_maxima_value: "最大降下量 {mm}mm / MAX DROP {mm}mm",
    test_estabilidad_5min: "安定性テスト (5分) / STABILITY TEST (5 MIN)",
    carretilla_demasiado_baja: "フォークリフトが低すぎます / FORKLIFT TOO LOW!",
    eleve_por_encima_de: "安定化を開始するには {cota} mm 以上に上げてください / Raise above {cota} mm to start stabilizing.",
    estabilizando_dots: "安定化中... / STABILIZING...",
    prueba_en_curso: "テスト実行中 / TEST IN PROGRESS",
    prueba_superada: "テスト合格 / TEST PASSED",
    alarmas_activas: "アクティブなアラーム / ACTIVE ALARMS",
    reset_alarmas: "アラームリセット / RESET ALARMS",
    no_alarmas_activas: "現在アクティブなアラームはありません / THERE ARE NO ACTIVE ALARMS AT THIS TIME.",
    log_alarmas: "アラーム履歴 / LOG_ALARMS",
    borrar_historico: "履歴削除 / CLEAR LOG",
    exportar_xlsx: ".xlsxエクスポート / EXPORT .XLSX",
    no_alarmas_historico: "履歴に登録されたアラームはありません / NO ALARMS REGISTERED IN THE LOG.",
    fecha_hora: "日時 / DATE & TIME",
    alarma_advertencia: "アラーム/警告 / ALARM / WARNING",
    descripcion: "説明 / DESCRIPTION",
    duracion: "期間 / DURATION",
    advertencia_label: "警告 / WARNING",
    alarma_label: "アラーム / ALARM",
    alarma_activa: "アクティブ / Active",
    vallas_no_posicion: "安全柵位置異常 / GATES NOT IN POSITION",
    peligro_jaula_no_segura: "危険: 安全柵が安全ではありません / DANGER: GAGE IS NOT SAFE",
    atencion_vallas_abajo: "！！ 警告：安全柵が下がっています ！！ / !! WARNING GATES DOWN !!",
    subirlas_al_finalizar: "テスト終了後に必ず上げてください / RAISE THEM WHEN TEST IS FINISHED",
    control_carga: "荷重管理 / LOAD CONTROL",
    peso_erp: "ERP登録重量 / ERP WEIGHT",
    peso_prueba: "テスト重量 / TEST WEIGHT",
    carga_actual: "現在の荷重 / CURRENT LOAD",
    pallets_multi: "({pallets} パレット × 250kg) / ({pallets} PALLETS × 250KG)",
    estado_prueba: "テスト状態 / TEST STATUS",
    esperando: "待機中... / WAITING...",
    espera_cota_subir: "{cota} mm 上昇待ち ↑ / WAIT {cota} MM ↑",
    ascenso_activo: "上昇中 / LIFT ACTIVE",
    descenso_activo: "下降中 / LOWER ACTIVE",
    prueba_ok: "テスト合格 ✓ / TEST OK ✓",
    prueba_nok: "テスト不合格 ✗ / TEST NOK ✗",
    espera_para_descender: "⟱ 下降待ち / WAIT TO DESCEND",
    midiendo: "● 測定中 / ● MEASURING",
    erp_objetivo: "ERP目標 / ERP TARGET:",
    prueba_elevacion_label: "昇降テスト / Elevation Test",
    elevacion_finalizada: "昇降完了 / LIFT FINISHED",
    inicio_descenso_en: "下降開始まで / Descent starts in",
    segundo: "秒 / second",
    segundos: "秒 / seconds",
    inicie_descenso: "↓ 下降を開始してください ↓ / ↓ Start Descent ↓",
    confirmando_senal_parada: "停止信号確認中... / Confirming stop signal...",
    carga_cota_incorrecta: "荷重または高さ異常 / INCORRECT LOAD OR HEIGHT",
    condiciones_no_cumplidas: "条件未充足 / Conditions not met",
    carga_no_corresponde: "荷重がERPの要求と一致しません。鉄製および木製パレットを確認してください / The load does not match the ERP requirements.",
    validacion_carga: "荷重検証 / LOAD VALIDATION",
    movimiento_incompleto: "動作未完了 / INCOMPLETE MOVEMENT",
    ascenso_incompleto: "上昇未完了 / Lift Incomplete",
    descenso_incompleto: "下降未完了 / Descent Incomplete",
    ascenso_incompleto_desc: "フォークリフトが必要な最大高さに達しませんでした。テストは中止されました / The forklift did not reach maximum height.",
    descenso_incompleto_desc: "フォークリフトが初期位置への下降を完了しませんでした。テストは中止されました / The forklift did not complete descent.",
    detenido_sin_completar: "動作未完了で停止 (タイムアウト 2秒) / Stopped without completing movement (timeout 2s)",
    caida_excesiva: "過度な降下 / EXCESSIVE DROP",
    repetir_prueba: "テストを再試行しますか？ / Repeat the test?",
    caida_excesiva_desc: "高さが設定された公差を下回りました ({subtitle}) / Height has dropped below configured tolerance.",
    resultado_fuera_tolerancia: "結果公差外 / RESULT OUT OF TOLERANCE",
    tiempos_no_cumplen_erp: "記録された時間がERPの公差を満たしていません / Recorded times do not meet ERP tolerances.",
    pulsador_fisico_detectado: "物理ボタンを検出... / Physical button detected...",
    si_repetir: "はい — 再試行 / YES — Repeat",
    click_iniciar: "クリックして開始 / Click to start",
    no_continuar: "いいえ — 続行 / NO — Continue",
    click_continuar: "クリックして続行 / Click to continue",
    iniciar_secuencia_sim: "シーケンス\n開始 / Start",
    pegatina_colocada_sim: "ステッカー\n貼付 / Sticker",
    abortar_secuencia_sim: "シーケンス\n中断 / Abort",
    jaula_label: "ケージ / Cage",
    subir_vallas_title: "ゲート上昇 / Raise Gates",
    bajar_vallas_title: "ゲート下降 / Lower Gates",
    pallets_sim_label: "パレット模擬 / Sim. Pallets",
    no_iniciar_alarmas_criticas: "シーケンスを開始できません：アクティブな致命的アラームがあります。 / Cannot start the sequence: Active critical alarms.",
    error_visor_3d: "3Dビューワエラー / 3D Viewer Error",
    error_visor_3d_desc: "3Dエンジンが故障しました。表示を復元するにはページを再読み込みしてください / The 3D engine failed. Reload page.",
    recargar_btn: "🔄 再読み込み / Reload",
    identificacion: "認証 / Identification",
    operario_codigo_apellidos: "コードまたは姓を入力してください / Enter your code or last name",
    confirmar_borrar_historico: "データベースからすべてのアラーム履歴を削除してもよろしいですか？ / Are you sure you want to delete all the alarm history from the database?",
    no_iniciar_modo_manual: "シーケンスを開始できません：機械が手動モードになっています。 / Cannot start the sequence: The machine is in MANUAL mode.",
    espera_arriba: "上部待機 / WAIT TOP",
    // PLC Modal & PLC variables
    Ob_Poner_Pegatina: "ステッカー貼付指示 / PLACE STICKER",
    Ob_Iniciar_Secuencia: "シーケンス開始 / START SEQUENCE",
    Ob_Abortar_Secuencia: "シーケンス中断 / ABORT SEQUENCE",
    Ib_LUZ_Pulsador_1: "ボタン1表示灯 / BUTTON 1 LIGHT",
    Ib_LUZ_Pulsador_2: "ボタン2表示灯 / BUTTON 2 LIGHT",
    Ib_LUZ_VERDE: "緑色積層信号灯 / GREEN BEACON",
    Ib_LUZ_AZUL: "青色積層信号灯 / BLUE BEACON",
    Ib_LUZ_ROJA: "赤色積層信号灯 / RED BEACON",
    Ib_EV_VALLA_REPOSO: "待機位置電磁弁 / REPOSE SOLENOID VALVE",
    Ib_EV_VALLA_TRABAJO: "作動位置電磁弁 / WORK SOLENOID VALVE",
    OW_Numero_Pallets: "パレット数 / NUMBER OF PALLETS",
    Ob_Bit_VIDA_PLC_APP: "ライフビット (PLC → APP) / PLC-APP HEARTBEAT",
    Ib_Bit_VIDA_APP_PLC: "ライフビット (APP → PLC) / APP-PLC HEARTBEAT",
    OR_Altura_Carretilla: "昇降レーザー測定高 / LASER LIFT HEIGHT",
    Ob_Trabajo_Cilindro_Valla_1: "安全柵1作動位置センサ / GATE 1 WORK SENSOR",
    Ob_Trabajo_Cilindro_Valla_2: "安全柵2作動位置センサ / GATE 2 WORK SENSOR",
    Ob_Reposo_Cilindro_Valla_1: "安全柵待機位置センサ / GATE REPOSE SENSOR",
    Ob_Estado_Automatico: "自動運転状態 (自動/手動) / AUTO-MANUAL STATE",
    OW_Tiempo_Elevacion: "上昇時間 / ELEVATION TIME",
    OW_Tiempo_Descenso: "下降時間 / DESCENT TIME",
    inicia_temporizador_ascenso: "上昇タイマ起動 / START ASCENT TIMER",
    inicia_temporizador_descenso: "下降タイマ起動 / START DESCENT TIMER",
    altura_relativa: "相対高さ (1m / 2m) / RELATIVE HEIGHT",
    consigna_posicion_altura: "高さ目標設定 (初期高さ) / TARGET INITIAL HEIGHT",
    Ob_Ready_Temporizador: "タイマ準備完了 (PLC) / TIMERS READY (PLC)",
    Ib_Restart_Temporizador: "タイマリセット (HMI) / RESTART TIMER (HMI)",
    dispositivos_encontrados: "検出デバイス / DEVICES FOUND",
    data_blocks_disponibles: "使用可能データブロック / AVAILABLE DATA BLOCKS",
    error_conexion: "接続エラー / CONNECTION ERROR",
    no_resultados: "結果が見つかりません / NO RESULTS FOUND",
    diag_config_plc: "PLC診断・設定 / PLC DIAGNOSIS & CONFIGURATION",
    monitor_control_opcua: "監視・制御・OPC UA / MONITORING, CONTROL & OPC UA",
    modo_simulacion_btn: "シミュレーションモード / SIMULATION MODE",
    conectado_plc_btn: "PLC接続中 / CONNECTED TO PLC",
    configuracion_opc_ua: "OPC UA設定 / OPC UA CONFIGURATION",
    ip_servidor_plc: "サーバIP (PLC) / SERVER IP (PLC)",
    buscando_dots: "検索中... / SEARCHING...",
    escanear_red: "ネットワークスキャン / SCAN NETWORK",
    puerto_opc_ua: "OPC UAポート / OPC UA PORT",
    nombre_db: "DB名 / DB NAME",
    consultando_dots: "クエリ実行中... / QUERYING...",
    buscar_en_plc: "PLC内検索 / FIND IN PLC",
    velocidad_escaneo_hz: "スキャンレート (Hz) / SCAN RATE (Hz)",
    namespace_ns: "ネームスペース (ns) / NAMESPACE (ns)",
    guardar_configuracion: "設定保存 / SAVE CONFIGURATION",
    desconectar_simulacion: "切断 (シミュレーションモード) / DISCONNECT (SIMULATION MODE)",
    config_plc_nota: "この設定はPythonアプリケーションにOPC UAサーバーの場所と、機械 de Siemens を示すDBを指示します / This configuration tells the Python app where to find OPC UA and which DB exposes the variables.",
    opcua_conectado: "OPC UA接続完了 / OPC UA CONNECTED",
    diagnosticando_conexion_dots: "接続診断中... / DIAGNOSING CONNECTION...",
    opcua_desconectado: "OPC UA切断 / OPC UA DISCONNECTED",
    tia_portal_cert_warn: "⚠️ 接続を許可するため、TIA Portal (Security > Certificate manager) で証明書を承認してください / Remember to approve the certificate in TIA Portal.",
    topologia_estado_conexion: "トポロジーと接続状態 / TOPOLOGY & CONNECTION STATUS",
    hmi_app_label: "HMIアプリ / HMI APP",
    opcua_connected_uppercase: "OPC UA 接続完了 / OPC UA CONNECTED",
    disconnected_uppercase: "切断 / DISCONNECTED",
    latencia: "レイテンシ / LATENCY",
    listado_variables_plc_db: "PLC変数リスト (DB) / PLC VARIABLES LIST (DB)",
    items_uppercase: "項目 / ITEMS",
    sin_variables_detectadas: "変数が検出されません / NO VARIABLES DETECTED",
    verifique_conexion: "接続を確認してください / VERIFY CONNECTION",
    config_vars_asignar_plc: "変数設定 — PLCとプロジェクトのマッピング / VARIABLE MAPPING",
    mapeadas_uppercase: "マッピング済み / MAPPED",
    modo_sim_forzado_activado: "シミュレーションモード: 強制有効 / SIMULATION MODE: FORCE ENABLED",
    deshabilitar_forzado_manual: "手動強制無効化 / DISABLE MANUAL OVERRIDE",
    habilitar_forzado_manual: "手動強制有効化 / ENABLE MANUAL OVERRIDE",
    in_lectura_plc_app: "IN (PLC読込 → アプリ) / IN (PLC READ → APP)",
    direccion: "方向 / DIRECTION",
    proyecto: "プロジェクト / PROJECT",
    plc_db: "PLC DB / PLC DB",
    valor: "値 / VALUE",
    no_vars_in_mapeadas: "マッピングされたIN変数はありません / NO MAPPED IN VARIABLES",
    out_escritura_app_plc: "OUT (アプリ書込 → PLC) / OUT (APP WRITE → PLC)",
    forzar: "強制設定 / FORCE",
    no_vars_out_mapeadas: "マッピングされたOUT変数はありません / NO MAPPED OUT VARIABLES",
    configuracion_alarmas: "アラーム設定 / ALARMS CONFIGURATION",
    in_alarmas_lectura_plc_app: "INアラーム (PLC読込 → アプリ) / IN ALARMS (PLC READ)",
    btn_anadir: "+ 追加 / + ADD",
    tipologia: "タイプ / TYPOLOGY",
    causa: "原因 / CAUSE",
    remedio: "対策 / REMEDY",
    select_option: "-- 選択 -- / -- SELECT --",
    no_alarmas_configuradas: "設定されたアラームはありません / NO CONFIGURED ALARMS",
    out_alarmas_escritura_app_plc: "OUTアラーム (アプリ書込 → PLC) / OUT ALARMS (APP WRITE)",
    out_escritura_option: "OUT (書込) / OUT (WRITE)",
    nombre_accion_placeholder: "アクション名 / ACTION NAME",
    // ERP Preview Card
    mastil_header: "マスト / MAST",
    mastil_ref: "マスト型式 / MAST REF",
    geometria: "幾何寸法 / GEOMETRY",
    cargas_y_capacidades: "荷重・容量 / LOADS & CAPACITIES",
    tpo_con_carga: "負荷運転時間 / TIME WITH LOAD",
    tpo_sin_carga: "無負荷運転時間 / TIME WITHOUT LOAD",
    elevacion_min: "最小上昇時間 / MIN ELEVATION",
    elevacion_max: "最大上昇時間 / MAX ELEVATION",
    descenso_min: "最小下降時間 / MIN DESCENT",
    descenso_max: "最大下降時間 / MAX DESCENT",
    cargar_secuencia_btn: "シーケンス読込 / LOAD SEQUENCE",
    cargar_secuencia_display: "シーケンス読込 ({displayTime}s) / LOAD SEQUENCE ({displayTime}s)",
    in_lectura_option: "IN (読込) / IN (READ)",
    ninguna_option: "-- なし / NONE --",
    sin_conexion_opcua: "OPC UA接続なし / NO OPC UA CONNECTION",
    ingrese_valor_para: "{varName} の値を入力してください / Enter value for {varName}",
    fijar_btn: "設定 / SET",
    toggle_btn: "切替 / TOGGLE",
    no_comandos_out_alarmas: "設定されたOUTアラームコマンドはありません / NO CONFIGURED ALARM OUT COMMANDS",
    protocolo_prueba: "テストプロトコル / Test Protocol",
    abortar: "中断 / Abort",
    identificar_carretilla: "フォークリフト識別 / Identify forklift",
    escaner: "スキャナー / Scanner",
    erp_btn: "ERP",
    esperando_lectura_dots: "スキャン待ち… / Waiting for scan…",
    escribe_bastidor: "車台番号を入力してください… / Enter chassis number…",
    buscar_en_erp: "ERP内検索 / Search in ERP",
    escribe_bastidor_enter: "車台番号を入力してEnterキーを押してください / Type the chassis number and press Enter",
    buscando_en_erp: "ERP内検索中… / Searching in ERP…",
    posicion_multiload: "マルチロード位置 / Multiload Position",
    altura_max: "最大高さ / Max Height",
    actual: "現在値 / Actual",
    esperando_iniciar_secuencia: "待機中: シーケンス開始を押してください / WAITING: Press START SEQUENCE",
    coloque_pegatina_desc: "ステッカーを貼ってください。確認のためにマストが正しい高さにある必要があります / Place the sticker. The mast must be at the correct height to confirm.",
    animacion_palet_en_curso: "パレット回収アニメーション実行中... / Pallet pickup animation in progress...",
    altura_incorrecta_desc: "高さが正しくありません。マストを範囲内に配置してください / Incorrect height. Position the mast within range.",
    pegatina_posicionada: "ステッカー貼付完了 / Sticker Positioned",
    sin_multiload_omitido: "最大高さ = 0 → マルチロードなし。ステップは省略されました / Max Height = 0 → No multiload. Step skipped.",
    pos_pegatina: "ステッカー位置 / Sticker pos.",
    test_sin_carga_prueba: "無負荷テスト - テスト / No load test - TEST",
    temporizadores_plc: "PLCタイマー / PLC Timers",
    esperando_condiciones: "条件待ち / WAITING FOR CONDITIONS",
    ascenso_activo_status: "上昇中 / LIFT ACTIVE",
    esperando_arriba_status: "上部待機中 / WAITING TOP",
    descenso_activo_status: "下降中 / LOWER ACTIVE",
    elevacion_finalizada_status: "昇降完了 / LIFT COMPLETED",
    prueba_nok_status: "テスト不合格 / TEST NOK",
    ascenso_s: "上昇 (秒) / Lift (s)",
    descenso_s: "下降 (秒) / Lower (s)",
    baje_por_debajo_de_iniciar: "開始するには {cota} mm 未満に下げてください / Lower below {cota} mm to start",
    listo_para_iniciar: "開始可能 / Ready to start",
    retira_carga_desc: "荷重を取り除いてテストを実行してください。カメラがサイクルタイムを記録します / Remove the load and run the test. The camera will record the cycle times.",
    elevacion_finalizada_msg: "昇降完了 / Elevation Completed",
    fallo_camara_sin_carga: "無負荷でのカメラテスト失敗。 / Camera test failure without load.",
    repetir_prueba_btn: "テスト再試行 / Repeat Test",
    continuar_btn: "続行 / Continue",
    pendiente_paso_anterior: "前ステップ未完了 / Pending previous step",
    test_con_carga_prueba: "荷重テスト - テスト / Load test - TEST",
    esperando_ascenso_cota: "上昇待ち (>{cota}M) / WAITING FOR LIFT (>{cota}M)",
    carga_carretilla_desc: "指定された荷重 ({peso} kg) を載せてテストを実行してください。カメラがサイクルタイムを記録します / Load the truck with the indicated capacity ({peso} kg) and run the test. The camera will record the cycle times.",
    animacion_palet_en_curso_load: "パレット動作中... / Pallet animation in progress...",
    fallo_camara_con_carga: "荷重状態でのカメラテスト失敗。 / Camera test failure under load.",
    prueba_5_minutos: "5分間テスト / 5 minutes test",
    altura_mastil: "マスト高さ / Mast height",
    eleve_por_encima_de_cota: "{cota} mm 以上に上げてください / Raise above {cota} mm",
    esperando_inicio_status: "開始待ち / WAITING FOR START",
    esperando_altura_status: "待機中: 高さ >{cota}M / WAITING: HEIGHT >{cota}M",
    estabilizando_3s_status: "安定化中 (3秒)... / STABILIZING (3s)...",
    prueba_en_curso_status: "テスト実行中 / TEST IN PROGRESS",
    prueba_ok_status: "テスト合格 / TEST OK",
    verifique_carga_desc: "現在の荷重が要求と一致していることを確認し、マストを {cota} mm 以上に上げてください。安定後、テストが自動的に開始されます / Verify that current load matches requirements and raise the mast above {cota} mm. The test will start automatically once stabilized.",
    altura_inicial: "初期高さ: / Initial height:",
    fallo_prueba_caida_excedida: "テスト失敗：許容降下量超過 / Test failure: height variation exceeded.",
    no_es_mx_xl_omitido: "モデル {modelo} → Mx/XL以外。ステップは省略されました / Model {modelo} → not Mx/XL. Step skipped.",
    prueba_5_minutos_superada: "5分間テスト合格 ✓ / 5 minutes test passed ✓",
    secuencia_completada: "シーケンス完了 / Sequence Completed",
    secuencia_completada_desc: "ログは自動的に保存されました。原点に戻ってください。注意：安全柵作動中（赤色信号灯） / Log saved automatically. Return to origin. Caution: Gates in operation (Red Beacon).",
    progreso: "進行状況 / Progress",
    cancelar_prueba: "テストキャンセル / Cancel test",
    secuencia_repetida: "リピートシーケンス / Repeated Sequence",
    secuencia_repetida_desc: "車台 {bastidor} は既にテスト済みです。再試行するステップを選択してください（不合格のステップがデフォルトで選択されます） / Chassis {bastidor} was already tested. Select which steps to repeat (failed steps are selected by default).",
    paso_2_multiload: "ステップ2: マルチロード / Step 2: Multiload",
    paso_3_sincarga: "ステップ3: 無負荷 / Step 3: No Load",
    paso_4_concarga: "ステップ4: 荷重あり / Step 4: With Load",
    paso_5_prueba5m: "ステップ5: 5分間テスト / Step 5: 5M Test",
    pulse_iniciar_secuencia_continuar: "続行するにはシーケンス開始を押してください / Press START SEQUENCE to continue",
    reiniciar_secuencia: "シーケンス再起動 / Restart sequence",
    baje_por_debajo_de_cota: "{cota} mm 未満に下げてください / Lower below {cota} mm",
    restaurar_etapa: "ステップを復元 / Restore step",
    deshabilitar_etapa: "ステップを無効化 / Disable step"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('appLanguage') || 'es';
  });

  const setLanguage = (lang) => {
    if (translations[lang]) {
      setLanguageState(lang);
      localStorage.setItem('appLanguage', lang);
      // Despachar evento para que otros componentes nativos fuera del árbol principal si los hubiera se sincronicen
      window.dispatchEvent(new Event('languageChanged'));
    }
  };

  const t = (key) => {
    if (!translations[language]) {
      return translations['es'][key] || key;
    }
    return translations[language][key] || translations['es'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
